[package]
name = "blueshift_vault"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
pinocchio = {version = "0.10.1"}
pinocchio-system = "0.5.0"
solana-address = {version = "2.0.0", features = ["curve25519"]}
shank = "0.4.6"